---
title: "Homework"
output: 
  html_document:
    theme: readable
    # toc: true
    # toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(eval = FALSE)
```

**What are ways that you can add a title to your graph? Select all that apply.**

  a. `labs(title = 'My Title')`
  b. `ggtitle('My Title')`
  c. `annotate('text', label = 'My Title', x = 2, y = max(df$y_value), size = 5.5)`
  d. `theme(title = element_text('My Title'))`

**Create a bar graph of cities/towns with greatest growth between 2010 and 2020**  
Using `ofm_april1_population_final_tidied.xlsx`...

  1. Subset for cities/towns and where year is 2010 or 2020
  2. Cast the data using the `dcast()` function from the `reshape2` package: 
      - `reshape2::dcast(<your data frame>, County + Jurisdiction ~ paste0("Year_", Year_chr), value.var = "Estimate")`
  3. Create a new column containing the difference
  4. Sort the data frame so that the difference column is in descending order
  5. Take the top 10 rows (use `head()`)
  6. Plot where cities/towns are on the x-axis and the y-axis displays total population estimate
      - Add thousands separator to the Y axis column
      - Angle the cities/town axis labels and reduce the font size
      - Change the y-axis title to something more descriptive
      - Add a title and source caption
  7. What order are the cities/town in? Can you reorder the cities/towns based on the value of the difference column?
      - convert the `Jurisdiction` column to a factor
      - use the `reorder()`


